version: "3.4"

services: 
  postman-prometheus-exporter-nodejs:
    image: mrmyiagi/postman-prometheus-exporter-nodejs
    container_name: postman-prometheus-exporter-nodejs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9013:8080"
      - "3001:3001"
    environment: 
      - SSO_URL=add_sso_url
      - CLIENT_ID=add_client_id
      - CLIENT_SECRET=add_client_secret
      - PARTNER_URL=add_partner_url
    restart: unless-stopped
